pull_request_rules:
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: automatic merge for github-actions pull requests affecting build.sbt
    conditions:
      - author=github-actions
      - check-success=ci
      - "#files=1"
      - files=build.sbt
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting project plugins.sbt
    conditions:
      - author=github-actions
      - check-success=ci
      - "#files=1"
      - files=project/plugins.sbt
    actions:
      merge:
        method: merge
  - name: semi-automatic merge for github-actions pull requests
    conditions:
      - author=github-actions
      - check-success=ci
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting project build.properties
    conditions:
      - author=github-actions
      - check-success=ci
      - "#files=1"
      - files=project/build.properties
    actions:
      merge:
        method: merge
  - name: automatic merge for github-actions pull requests affecting .scalafmt.conf
    conditions:
      - author=github-actions
      - check-success=ci
      - "#files=1"
      - files=.scalafmt.conf
    actions:
      merge:
        method: merge
